name: CI
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step1
        uses: actions/checkout@v2
      - name: Test
        run: chmod +x ci/test.sh 
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

